{% set version = "2.5.0" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: https://github.com/stevengj/nlopt/archive/v{{ version }}.tar.gz
  sha256: c6dd7a5701fff8ad5ebb45a3dc8e757e61d52658de3918e38bab233e7fd3b4ae

build:
  number: 0

requirements:
  build:
    - cmake
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL 2.1
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
