{% set version = "2.10.1" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: https://github.com/stevengj/nlopt/archive/v{{ version }}.tar.gz
  sha256: 30d13ce16da119db3e987784f7864e35a562ec62c186352fae55cd003e6c58ff

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('nlopt', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python

test:
  imports:
    - nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
