{% set version = "2.8.0" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: https://github.com/stevengj/nlopt/archive/v{{ version }}.tar.gz
  sha256: e02a4956a69d323775d79fdaec7ba7a23ed912c7d45e439bc933d991ea3193fd
  patches:
    - py313.patch
    - metadata.patch

build:
  number: 2
  skip: true  # [python_impl == 'pypy']
  run_exports:
    - {{ pin_subpackage('nlopt', max_pin='x.x') }}

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - make  # [unix]
    - swig
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - numpy
  run:
    - python

test:
  imports:
    - nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
