{% set version = "2.7.0" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: https://github.com/stevengj/nlopt/archive/v{{ version }}.tar.gz
  sha256: b881cc2a5face5139f1c5a30caf26b7d3cb43d69d5e423c9d78392f99844499f
  patches:
      - setup.py.patch
      - cmake-FindNumPy.cmake.patch
      - CMakeLists.txt.patch
      - src-swig-CMakeLists.txt.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('nlopt', max_pin='x.x') }}
  script: {{ PYTHON }} -m pip install . -vv --install-option="-GNinja"

requirements:
  build:
    - swig
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - numpy
    - pip
    - python
    - scikit-build
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - nlopt
    - _nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL-2.1-or-later
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
