{% set version = "2.4.2" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: http://ab-initio.mit.edu/nlopt/nlopt-{{ version }}.tar.gz
  md5: d0b8f139a4acf29b76dbae69ade8ac54

build:
  number: 0
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>35]
  skip: true  # [win and py>35]

requirements:
  build:
    - python
    - numpy  # [not win]

  run:
    - python  # [not win]
    - numpy  # [not win]

test:
  imports:
    - nlopt  # [not win]

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL 2.1
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
