{% set version = "2.4.2" %}

package:
  name: nlopt
  version: {{ version }}

source:
  fn: nlopt-{{ version }}.tar.gz
  url: http://ab-initio.mit.edu/nlopt/nlopt-{{ version }}.tar.gz
  md5: d0b8f139a4acf29b76dbae69ade8ac54

build:
  number: 2

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - swig
    - python
    - numpy         # [not (win and (py35 or py36))]
    - numpy         # [win and py35]
    - numpy         # [win and py36]

  run:
    - python
    - {{ pin_compatible('numpy') }}    # [not (win and (py35 or py36))]
    - {{ pin_compatible('numpy') }}    # [win and py35]
    - {{ pin_compatible('numpy') }}   # [win and py36]

test:
  imports:
    - nlopt

about:
  home: http://ab-initio.mit.edu/nlopt
  license: LGPL 2.1
  license_file: COPYING
  summary: nonlinear optimization library

extra:
  recipe-maintainers:
    - jschueller
