appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bg/NwThp3mXhcUVQ5fmLeAnRqHYXGDn92RYpm6SXvFzI1eq5QuBaAzWQxQ6JfouXaEzdXGrC09Fmd06GuHx7dvwHn9RK9DW9PkH5oF9unYMOC3el121ZW/I6t/ynDAl06QRNfKVVcacbcGr6v6ssffxuixE+EaEF4rgcN11TFfGj57n9hqqihflcCvffdHgVREqV2oLZK7D/BdB9s9znHsKFQSm6ODdhEX2nsKB+cFtujmmsM2KCpOUPz8j/B9Chep/2/AXv4T+oJIk4yMEatevD1c5BOCfhm/eMjUJ9Cple+blvOz4H+eszr8rhDbY+CUuFV/+7JWxNf6rW1+yFWjxvkdsbExHXpSNmGij2W9u9l3GSPR1DKnvkEC9wNizeyauDMdXUuf753/MKa6GePcJqoKMelsqEfEupbrXnaXlyc5K9zltEKEMfQA4xw8TeKe6TDaAsJaKDNeIZs7PvWSmCuoFE3zePau2NSBhVf4QnXFvxF62l6WrChtBo0TsnYnvmrsJHefLBtjq7LrpkbCk+Ye37XmS8cBy0A6C0dPcAYblL4gWnZ/Fnryz3r4s1iIbm8CFQbROHDVUXtQYyyeFBZowcaLtChZNlC8JdgrzOamo4Aaa3ilnA3+1OiCTIDadmn8+0gjbJtuWI5Wok9RPiC0k/pBavDyEbtuDwAzs=}
